---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-public
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-public
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["list","watch","get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-public-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-public
subjects:
- kind: ServiceAccount
  name: external-dns-public
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-public
  namespace: default
spec:
  replicas: 1 
  selector: 
    matchLabels: 
      app: external-dns-public 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns-public
    spec:
      serviceAccountName: external-dns-public
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.13.4 
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=interview-lgc.com
        - --provider=aws
        - --policy=sync
        - --aws-zone-type=public
        - --registry=txt
        - --txt-owner-id=interview.k8s.pub
        - --log-level=debug
        - --interval=30s
        - --annotation-filter=external-dns.alpha.kubernetes.io/access in (public)
        resources:
          limits:
            memory: 50Mi
            cpu: 10m
          requests:
            memory: 25Mi
            cpu: 5m
--- 